# Generated by Django 3.0.7 on 2020-06-18 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=20)),
                ('number_of_stages', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('winner',
                 models.ForeignKey(on_delete=models.SET('Deleted user'), to='rest_tournament_manager_app.PlayerModel')),
            ],
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('stage', models.IntegerField()),
                ('player_a_score', models.IntegerField(default=0)),
                ('player_b_score', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('player_a', models.ForeignKey(on_delete=models.SET('Deleted user'), related_name='player_a',
                                               to='rest_tournament_manager_app.PlayerModel')),
                ('player_b', models.ForeignKey(on_delete=models.SET('Deleted user'), related_name='player_b',
                                               to='rest_tournament_manager_app.PlayerModel')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='rest_tournament_manager_app.TournamentModel')),
            ],
        ),
    ]
