# Generated by Django 3.0.7 on 2020-06-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_tournament_manager_app', '0002_auto_20200620_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmodel',
            name='match_players',
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='tournament_is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentmodel',
            name='tournament_players',
            field=models.ManyToManyField(to='rest_tournament_manager_app.PlayerModel'),
        ),
    ]
