# Generated by Django 3.0.7 on 2020-06-20 17:46

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('rest_tournament_manager_app', '0004_auto_20200620_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermodel',
            old_name='player_first_name',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='playermodel',
            name='player_last_name',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='player_birth_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 17, 46, 50, 696508, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='player_mail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
