# Generated by Django 3.0.7 on 2020-06-20 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_tournament_manager_app', '0005_auto_20200620_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='tournament_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='player_birth_date',
            field=models.DateTimeField(),
        ),
    ]
