# Generated by Django 3.0.7 on 2020-06-20 19:05

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('rest_tournament_manager_app', '0007_auto_20200620_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='player_birth_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 6, 20, 19, 5, 36, 645471, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tournamentmodel',
            name='tournament_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 19, 5, 36, 645942, tzinfo=utc)),
        ),
    ]
