# Generated by Django 3.0.7 on 2020-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rest_tournament_manager_app', '0010_auto_20200620_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='tournament_max_number_of_players',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
